export * from "./BarraNav/BarraNav";
export * from "./Contacto/Contacto";
export * from "./Footer/Footer";
export * from "./SeccionExperiencia/SeccionExperiencia";
export * from "./SeccionHero/SeccionHero";
export * from "./SectionProyectos/SectionProyectos";
export * from "./Skill/Skill";
export * from "./SobreMi/SobreMi";
export * from "./UpButton/UpButton";
